version: '2.18'
volumes:
  pg_data_prodaction:
  static_volume:
services:
  db:
    image: postgres:13.10-alpine3.17
    env_file: .env
    volumes:
      - pg_data_prodaction:/var/lib/postgresql/data
  backend:
    image: kafartem/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db
  frontend:
    image: kafartem/taski_frontend
    env_file:
      - .env
    volumes:
      - static_volume:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    image: kafartem/taski_gateway
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80