version: '2.18'
volumes:
  pg_data:
  static:
services:
  db:
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      gateway:
        condition: service_started

  frontend:
    env_file: .env
    build: ./frontend
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
    depends_on:
      db:
        condition: service_started

  gateway:
    build: ./gateway
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      frontend:
        condition: service_completed_successfully